spring:
  application:
    name: eureka-client
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除
    lease-expiration-duration-in-seconds: 5
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒
    lease-renewal-interval-in-seconds: 5