eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
    #心跳时间间隔
    lease-renewal-interval-in-seconds: 5
  server:
    enable-self-preservation: false
    #剔除失效服务间隔
    eviction-interval-timer-in-ms: 5000
server:
  port: 8761
spring:
  application:
    name: eurka-server