spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zangsh/springcloud
          search-paths: config
          username:
          password:
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: zangsh
    password: 123456
server:
  port: 8889
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh